### ISSUE TITLE
VSCode 1.20.0 stopped overriding cursor

### ISSUE THREAD

**Issue by digitaldrummerj** [johnpapa/vscode-winteriscoming#7] opened 2018-02-09 21:37 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

When I updated to VSCode to 1.20.0 the underline thin cursor override stopped working and it is just the normal underline-thin cursor.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution).macOS(Yosemite ? El Capitan? Sierra ?)

Windows 10

### Versions
  > VSCode: 1.20.0
  > Winter is Coming: 0.4.7

### Repro steps
  > Setup theme as normal with the custom css file and the cursor wasn't overriden.

### The log given by the failure.
>See Video at https://www.dropbox.com/s/1cau5ewgqume86d/Cursor-Error.mp4?dl=0

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment] 2018-03-03 14:38
I'm not seeing this ... can you clarify in the video or screen shots what the issue is?

**Comment by digitaldrummerj** [comment] 2018-03-10 21:38
The underline thin cursor used to be overridden in the custom css to make it a tall and wide cursor but now it is just showing the underline thin cursor.  In the video the cursor in on line 16.  It is almost impossible to see the cursor.  I ended up removing the cursor setting so that I could get a normal vertical cursor again.

**Comment by johnpapa** [comment] 2019-05-30 11:20
closing - please reopen with details if this still is an issue

**Closed by johnpapa** 2019-05-30 11:20 UTC
